version: '3.9'

services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
      - "10050:10050"
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_ACTIVE_CHECKS_SERVER=${ZBX_SERVER_HOST}
    pid: "host"
    # Grant extended kernel capabilities for low-level monitoring
    privileged: true
    volumes:
      # Mounts the host's filesystems into the container in read-only mode
      - /:/host/root:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginxlog-exporter:
    image: 'kbudde/nginx-log-exporter:latest'
    container_name: nginxlog-exporter
    ports:
      - "4040:4040"
    volumes:
      - /var/log/nginx:/var/log/nginx:ro 
    command:
      - '--path=/var/log/nginx/access.log'
      - '--format=$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'

  zabbix-sender:
    build: ./zabbix_sender/
    container_name: zabbix-sender
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts:ro
      - ./.env:/scripts/.env:ro
    environment:
      - TZ=UTC
